version: '3'

volumes:
  bundle:

services:
  app:
    build: .
    ports:
      - "3000:3000" # http
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./config/database.docker.yml:/usr/src/app/config/database.yml
      - ./config/application.example.yml:/usr/src/app/config/application.yml
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: postgres
