default: &default
  host: db
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres

development:
   <<: *default
   database: corporate_development

test:
  <<: *default
  database: corporate_test
